//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_TrabajoFidelitas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MotoresBritanicosEntities : DbContext
    {
        public MotoresBritanicosEntities()
            : base("name=MotoresBritanicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<IniciarSesionUsuario_Result> IniciarSesionUsuario(string emailUsuario, string contrasenaUsuario)
        {
            var emailUsuarioParameter = emailUsuario != null ?
                new ObjectParameter("emailUsuario", emailUsuario) :
                new ObjectParameter("emailUsuario", typeof(string));
    
            var contrasenaUsuarioParameter = contrasenaUsuario != null ?
                new ObjectParameter("contrasenaUsuario", contrasenaUsuario) :
                new ObjectParameter("contrasenaUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IniciarSesionUsuario_Result>("IniciarSesionUsuario", emailUsuarioParameter, contrasenaUsuarioParameter);
        }
    
        public virtual int RegistrarUsuario(string contrasenaUsuario, string nombreUsuario, string emailUsuario)
        {
            var contrasenaUsuarioParameter = contrasenaUsuario != null ?
                new ObjectParameter("contrasenaUsuario", contrasenaUsuario) :
                new ObjectParameter("contrasenaUsuario", typeof(string));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var emailUsuarioParameter = emailUsuario != null ?
                new ObjectParameter("emailUsuario", emailUsuario) :
                new ObjectParameter("emailUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarUsuario", contrasenaUsuarioParameter, nombreUsuarioParameter, emailUsuarioParameter);
        }
    }
}
